DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS observed;

CREATE TABLE user (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL,
	profile_pic TEXT NOT NULL
);

CREATE TABLE observed (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	uid TEXT NOT NULL,
	obs_date TIMESTAMP NOT NULL,
	phase TEXT NOT NULL,
	FOREIGN KEY (uid) REFERENCES user(id)
);
