DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS favorite;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	longitude INTEGER NOT NULL,
	latitude INTEGER NOT NULL
);

CREATE TABLE favorite (
	id INTEGER PRIMARY KEY AUTOINCREMENT
);
